default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dns_search_development

test:
  <<: *default
  database: dns_search_test

production:
  <<: *default
  database: dns_search_production
  username: dns_search
  password: <%= ENV['DNS_SEARCH_DATABASE_PASSWORD'] %>
